=== killoff/amc/app/code/Magento/Indexer/etc/indexer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="indexer" type="indexerType" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueIndexertId">
            <xs:annotation>
                <xs:documentation>
                    Indexer Id must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="indexer" />
            <xs:field xpath="@id" />
            <xs:field xpath="@view_id" />
        </xs:unique>
        <xs:unique name="uniqueViewId">
            <xs:annotation>
                <xs:documentation>
                    Indexer Id must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="indexer" />
            <xs:field xpath="@view_id" />
        </xs:unique>
    </xs:element>

    <xs:complexType name="indexerType">
        <xs:annotation>
            <xs:documentation>
                Indexer declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="title" type="translatableType" />
            <xs:element name="description" type="translatableType" />
            <xs:element name="fields" type="fieldsType"  minOccurs="0" maxOccurs="1">
                <xs:unique name="uniqueField">
                    <xs:selector xpath="field"/>
                    <xs:field xpath="@name"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="view_id" type="viewIdType" use="required" />
        <xs:attribute name="class" type="classType" use="required" />
    </xs:complexType>

    <xs:complexType name="translatableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="translate" use="optional" fixed="true" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="viewIdType">
        <xs:annotation>
            <xs:documentation>
                View ID can contain only [a-zA-Z0-9_].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="classType">
        <xs:annotation>
            <xs:documentation>
                Class name can contain only [a-zA-Z\].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z\\]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="fieldsType">
        <xs:annotation>
            <xs:documentation>
                Index fields declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="field" type="fieldTypeAbstract" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="handler" type="classType" use="required"/>
    </xs:complexType>

    <xs:complexType name="fieldTypeAbstract">
        <xs:annotation>
            <xs:documentation>
                Index field declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="origin" type="originType" use="required"/>
        <xs:attribute name="handler" type="classType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="originType">
        <xs:annotation>
            <xs:documentation>
                Origin can contain only [a-zA-Z0-9_.].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]+\.[a-zA-Z0-9_]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="match">
        <xs:complexContent>
            <xs:extension base="fieldTypeAbstract">
                <xs:sequence>
                    <xs:element type="filterType" name="filter" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="filterType">
        <xs:annotation>
            <xs:documentation>
                Index field filter.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="class" type="classType" use="required"/>
    </xs:complexType>

    <xs:complexType name="both">
        <xs:complexContent>
            <xs:extension base="match"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="filter">
        <xs:complexContent>
            <xs:extension base="fieldTypeAbstract">
                <xs:attribute type="dataType" name="dataType" use="required" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="dataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="int" />
            <xs:enumeration value="float" />
            <xs:enumeration value="varchar" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== killoff/amc/dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Indexer/_files/valid_indexer.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../../app/code/Magento/Indexer/etc/indexer.xsd">
    <indexer id="indexer_1" view_id="catalogsearch_fulltext" class="Magento\CatalogSearch\Model\Indexer\Fulltext">
        <title translate="true">Test Indexer Declaration 1</title>
        <description translate="true">Test Indexer Declaration 1</description>
        <fields handler="Magento\Framework\Search\Index\Fields\Handler">
            <field name="title" origin="table_name.field_name" handler="Magento\Framework\Search\Index\Field\Handler\Class" xsi:type="both">
                <filter class="Magento\Framework\Search\Index\Filter\StopWordsFilter"/>
            </field>
            <field name="description" origin="table_name.field_name" handler="Magento\Framework\Search\Index\Field\Handler\Class" xsi:type="match">
                <filter class="Magento\Framework\Search\Index\Filter\LowercaseFilter"/>
            </field>
            <field name="visibility" origin="table_name.field_name" handler="Magento\Framework\Search\Index\Field\Handler\Class" xsi:type="filter" dataType="int" />
        </fields>
    </indexer>
</config>
