=== killoff/amc/app/code/Amc/Consultation/etc/layout.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="layout" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="field" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute type="xs:string" name="name" use="optional"/>
                                            <xs:attribute type="xs:string" name="type" use="optional"/>
                                            <xs:attribute type="xs:byte" name="protocol_id" use="optional"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="optional"/>
                        <xs:attribute type="xs:string" name="label" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== killoff/amc/app/code/Amc/Consultation/etc/layout.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Amc_Consultation:etc/layout.xsd">
    <layout name="generic" label="Generic">
        <field name="user_date" type="date" label="Date" required="1" />
        <field name="comment" type="editor" label="Comment" required="1" />
        <field name="conclusion" type="editor" label="Conclusion" wysiwyg="true" state="html" style="height: 250px;" />
        <field name="recommendation" type="editor" label="Recommendation" />
    </layout>
    <layout name="uzi" label="USD">
        <field name="comment" type="textarea" />
        <field name="conclusion" type="textarea" />
        <field name="recommendation" type="protocol" protocol_id="12" />
    </layout>
</config>
